version: '3.1'
services:
  app:
    container_name: customer-app
    image: customer-app
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgrescontainer:5432/customerdb
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgrescontainer
  postgrescontainer:
    image: postgres
    container_name: postgrescontainer
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=customerdb